### ISSUE TITLE
Socks4 support

### ISSUE THREAD

**Issue by bawzz234** [restyler/proxy-checker-cli#2]
Hi, 

Great work on this project. Threading works beautifully and https checking is perfect. Can you please add Socks4 support for checking? Would be greatly appreciated. 

Best Regards

**Comment by restyler** [comment]
Hey! Sure. socks4 support was just implemented in 2.0.9 - reinstall from npm to test it.
```proxy-checker-cli testips.txt --protocol=socks4 --code=20. ```

**Comment by bawzz234** [comment]
I appreciate your effort on it. It works perfectly fine. Checks also very accurately. Thanks.

I have found some issues on other functions, I have opened an issue. Feel free to check it out whenever you can. 

Best Regards
