### ISSUE TITLE
To make progress bar visible when -s is turned on | New feature request: -table on/off

### ISSUE THREAD

**Issue by bawzz234** [restyler/proxy-checker-cli#4]
Hello,

Just tried the latest version. Thanks for fixing the -s issue. Proxies are now checking and saving is also working properly. Can you please make the progress bar visible when -s mode is on. Would be very useful to see the progression of checking. 

- [ ]  Can you please also add another function to disable table reporting after finish of the checking (-table off and on) It will be very useful when checked big proxy lists. It is useful to have the table reporting for small amount of proxies. But when it comes to big proxy lists, it can take long time to finish the table and it uses lots of resources as well. So having an option to turn it off when needed would be useful.

Best Regards

**Comment by restyler** [comment]
Hi!
Well, -s option is designed to suppress all the output. E.g. cron does not need progress bar :)
I guess --hide-results-table bool option might be what we need here?

**Comment by bawzz234** [comment]
Indeed, that makes sense on -s. Yeah, hiding the table results would be very useful when checking big proxy lists. It will save lots of resources and time. 

Thanks in advance for adding it. :)

Best Regards

**Comment by restyler** [comment]
`--notable` option was added to 2.0.11 (already on npm)

**Comment by bawzz234** [comment]
Hello, 

Just tested the latest version. Working perfectly, no lag and no resources were harmed when used big proxies. Thanks for adding this option. 

Best Regards
